import type { ToolDefinition } from "@/types/tools";

export const tools: ToolDefinition[] = [
  {
    slug: "comprimir-pdf",
    name: "Comprimir PDF",
    description: "Reduza o tamanho do PDF mantendo a qualidade.",
    seoDescription:
      "Comprimir PDF Online Grátis — Reduza o tamanho de arquivos PDF pesados mantendo a máxima qualidade visual. Sem cadastro e 100% seguro.",
    seoTitle: "Comprimir PDF Online Grátis e Rápido",
    icon: "compress",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: true,
  },
  {
    slug: "juntar-pdf",
    name: "Juntar PDF",
    description: "Una vários PDFs em um único arquivo.",
    seoDescription:
      "Juntar PDF Online — Combine múltiplos arquivos PDF em um único documento de forma rápida e fácil. Organize páginas e unifique PDFs grátis.",
    seoTitle: "Juntar PDF Online Grátis — Unir Arquivos",
    icon: "merge",
    tier: 1,
    accept: [".pdf"],
    multiple: true,
    usesBinary: false,
  },
  {
    slug: "dividir-pdf",
    name: "Dividir PDF",
    description: "Extraia páginas ou intervalos de um PDF.",
    seoDescription: "Dividir PDF Online — Extraia páginas ou intervalos específicos do seu PDF de forma simples, gratuita e segura.",
    seoTitle: "Dividir PDF Online Grátis por Páginas",
    icon: "split",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: false,
  },
  {
    slug: "extrair-paginas",
    name: "Extrair Páginas",
    description: "Separe páginas selecionadas em PDFs individuais dentro de um .zip.",
    seoDescription: "Extraia páginas do PDF online grátis e baixe cada página como PDF individual em um arquivo ZIP.",
    seoTitle: "Extrair Páginas de PDF Online Grátis",
    icon: "extract-pages",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: false,
  },
  {
    slug: "pdf-para-word",
    name: "PDF para Word",
    description: "Converta PDF em documento Word editável.",
    seoDescription:
      "Converter PDF para Word Online — Transforme seus arquivos PDF em documentos DOCX editáveis mantendo a formatação original. Grátis e rápido.",
    seoTitle: "Converter PDF para Word Online Grátis",
    icon: "pdf-to-word",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: true,
  },
  {
    slug: "pdf-para-txt",
    name: "PDF para TXT",
    description: "Extraia apenas o texto do PDF em arquivo .txt.",
    seoDescription:
      "Converter PDF para TXT Online — Extraia o conteúdo de texto de qualquer PDF de forma instantânea para reutilização em outros editores.",
    seoTitle: "Converter PDF para TXT Online Grátis",
    icon: "pdf-to-txt",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: false,
  },
  {
    slug: 'pdf-para-jpg',
    name: 'PDF para JPG',
    description: 'Converta páginas do PDF em imagens JPG.',
    seoDescription: 'Converter PDF para JPG Online — Transforme páginas de PDF em imagens JPG de alta resolução. Grátis, seguro e sem marcas d\'água.',
    seoTitle: 'Converter PDF para JPG Online Grátis',
    icon: 'pdf-to-jpg',
    tier: 1,
    accept: ['.pdf'],
    multiple: false,
    usesBinary: true,
  },
  {
    slug: "jpg-para-pdf",
    name: "JPG para PDF",
    description: "Una suas imagens em um único PDF.",
    seoDescription: "Converter JPG para PDF Online — Transforme suas fotos e imagens JPG em um documento PDF organizado de forma simples e gratuita.",
    seoTitle: "Converter JPG para PDF Online Grátis",
    icon: "jpg-to-pdf",
    tier: 1,
    accept: [".jpg", ".jpeg", ".png"],
    multiple: true,
    usesBinary: false,
  },
  {
    slug: "rodar-pdf",
    name: "Rodar PDF",
    description: "Gire páginas do PDF em qualquer ângulo.",
    seoDescription:
      "Rotacione páginas de PDF online grátis. Gire 90°, 180° ou 270° e baixe o PDF pronto em segundos.",
    seoTitle: "Rodar PDF Online Grátis — Girar Páginas",
    icon: "rotate",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: false,
  },
  {
    slug: "organizar-pdf",
    name: "Organizar PDF",
    description: "Reordene ou exclua páginas do PDF.",
    seoDescription:
      "Reordene páginas de PDF online grátis com drag & drop. Exclua páginas indesejadas e baixe o PDF organizado.",
    seoTitle: "Organizar PDF Online Grátis e Fácil",
    icon: "organize",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: false,
  },
  {
    slug: "proteger-pdf",
    name: "Proteger PDF",
    description: "Adicione senha ao PDF para proteger o acesso.",
    seoDescription: "Proteja PDFs com senha online grátis. Seus arquivos não são armazenados.",
    seoTitle: "Proteger PDF com Senha Online Grátis",
    icon: "protect",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: true,
  },
  {
    slug: "marca-dagua",
    name: "Marca d'Água",
    description: "Adicione texto de marca d'água em todas as páginas.",
    seoDescription: "Adicione marca d'água em PDF online grátis. Personalize texto, cor e opacidade.",
    seoTitle: "Marca d'Água em PDF Online Grátis e Seguro",
    icon: "watermark",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: false,
  },
  {
    slug: "numerar-paginas",
    name: "Numerar Páginas",
    description: "Adicione numeração automática no cabeçalho ou rodapé do PDF.",
    seoDescription: "Numere páginas de PDF online grátis. Escolha cabeçalho ou rodapé e baixe o PDF pronto.",
    seoTitle: "Numerar Páginas de PDF Online Grátis",
    icon: "page-numbers",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: false,
  },
  {
    slug: "pdf-para-png",
    name: "PDF para PNG",
    description: "Converta páginas do PDF em imagens PNG com fundo transparente.",
    seoDescription: "Converta PDF para PNG online grátis. Fundo transparente, ideal para design.",
    seoTitle: "Converter PDF para PNG Online Grátis",
    icon: "pdf-to-png",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: true,
  },
  {
    slug: "redigir-pdf",
    name: "Censurar PDF",
    description: "Oculte permanentemente informações sensíveis com retângulos pretos.",
    seoDescription: "Censure dados e oculte informações em PDF online grátis. Retângulos pretos permanentes, sem possibilidade de recuperação.",
    seoTitle: "Censurar PDF Online Grátis — Ocultar Dados",
    icon: "redact",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: false,
  },
  {
    slug: "pdf-para-markdown",
    name: "PDF para Markdown",
    description: "Converta PDF em Markdown estruturado, ideal para RAG e IA.",
    seoDescription: "Converta PDF para Markdown online grátis. Extrai texto com títulos e listas — perfeito para LLMs, RAG, LangChain e LlamaIndex.",
    seoTitle: "Converter PDF para Markdown Online Grátis",
    icon: "pdf-to-markdown",
    tier: 1,
    accept: [".pdf"],
    multiple: false,
    usesBinary: false,
  },
];

export function getTool(slug: string): ToolDefinition {
  const tool = tools.find((t) => t.slug === slug);
  if (!tool) throw new Error(`Tool not found: ${slug}`);
  return tool;
}
