server {
    listen 80;
    server_name pdf.unificando.com.br;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name pdf.unificando.com.br;

    ssl_certificate     /etc/letsencrypt/live/pdf.unificando.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pdf.unificando.com.br/privkey.pem;

    # Alinhado com MAX_FILE_SIZE + margem para headers
    client_max_body_size 55M;

    location / {
        proxy_pass         http://unificando-pdf:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;

        # Timeout generoso para LibreOffice e Ghostscript
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
